version: '3'

services:
  ebisusbay-frontend:
    container_name: ebisusbay-frontend
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    environment:
      PORT: 8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:80 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    ports:
      - 8080:80
